spring:
  data:
    mongodb:
      username: mustopha
      password: ayinde_99
      host: localhost
      port: 5003
      authentication-database: admin
      database: notification
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.abuhanaan.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.abuhanaan.ecommerce.notification.request.PaymentNotificationRequest
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username: mustopha
    password: ayinde_99
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040